name: Deploy to Ubuntu

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            if [ ! -d /opt/tin-bot ]; then sudo mkdir -p /opt/tin-bot; sudo chown $USER:$USER /opt/tin-bot; fi
            if [ ! -d /opt/tin-bot/.git ]; then
              cd /opt/tin-bot
              git clone https://github.com/${{ github.repository }} .
            fi
            # Write repo remote to match current
            cd /opt/tin-bot
            if ! git remote get-url origin | grep -q "${{ github.repository }}"; then
              git remote set-url origin https://github.com/${{ github.repository }}
            fi
            bash ./deploy/deploy.sh
